name: F5 CLA

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.ref_name }}-cla

permissions:
  contents: read

jobs:
  f5-cla:
    name: F5 CLA
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Run F5 Contributor License Agreement (CLA) assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have hereby read the F5 CLA and agree to its terms') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@f41946747f85d28e9a738f4f38dbcc74b69c7e0e # v2.5.1
        with:
          # Any pull request targeting the following branch will trigger a CLA check.
          branch: "main"
          # Path to the CLA document.
          path-to-document: "https://github.com/f5/.github/blob/main/CLA/cla-markdown.md"
          # Custom CLA messages.
          custom-notsigned-prcomment: "ðŸŽ‰ Thank you for your contribution! It appears you have not yet signed the F5 Contributor License Agreement (CLA), which is required for your changes to be incorporated into an F5 Open Source Software (OSS) project. Please kindly read the [F5 CLA](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md) and reply on a new comment with the following text to agree:"
          custom-pr-sign-comment: "I have hereby read the F5 CLA and agree to its terms"
          custom-allsigned-prcomment: "âœ… All required contributors have signed the F5 CLA for this PR. Thank you!"
          # Remote repository storing CLA signatures.
          remote-organization-name: "f5"
          remote-repository-name: "f5-cla-data"
          path-to-signatures: "signatures/beta/signatures.json"
          # Comma separated list of usernames for maintainers or any other individuals who should not be prompted for a CLA.
          allowlist: bot*
          # Do not lock PRs after a merge.
          lock-pullrequest-aftermerge: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.F5_CLA_TOKEN }}
